### ISSUE TITLE
Cannot create world due to datapack issues (1.6)

### ISSUE THREAD

**Issue by Ryutodabi** [blay09/ExCompressum#304] opened 2021-02-26 00:45 UTC
Hey! For some reason, Compressum has stalled out my game-- I'm confused, and I really need help. This mod is super necessary for using the sieve to me. lol

[latest.log](https://github.com/blay09/ExCompressum/files/6046701/latest.log)

**Comment by BlayTheNinth** [comment] 2021-02-28 13:26
Duplicate of #302

**Closed as completed by BlayTheNinth** 2021-02-28 13:26 UTC
Labels: Bug
