### ISSUE TITLE
Graphical (?) Issue when using Auto Hammers

### ISSUE THREAD

**Issue by xdelphii** [blay09/ExCompressum#326] opened 2021-07-26 14:26 UTC
This bug report was mistakenly reported over at Ex Nihilo (core mod) and actually pertains to the auto hammers here. As I am utterly useless at navigating GitHub, I hope this is the correct location and the issue is not one already reported/flagged/resolved in upcoming patch. 

**Describe the bug**
Auto hammers/heavy auto hammers causing graphical errors (?) when actively hammering stone. The error includes a large diamond/square around the sun and makes other items flicker between visible/invisible or remain entirely invisible. 
It remains functional, but the visual impact is persistent and incompatible with playing (as you can't see things around you, but for their thin black outline)

**To Reproduce**
Place auto hammer/heavy auto hammer (no issue)
Power auto hammer/heavy auto hammer (no issue)
Provide or connect to source of cobblestone, machine begins working and graphical errors commence. 

**Expected behavior**
No disappearing items around it.

**Screenshots**
![2021-07-26_14 41 53](https://user-images.githubusercontent.com/87985958/127000856-11c07ecf-7b44-451f-84a6-785da5a43e3f.png)
SCREENSHOT 1: Auto sieve setup, powered and working (no issues)

![2021-07-26_14 42 09](https://user-images.githubusercontent.com/87985958/127000958-b470bf2b-70aa-45a7-9832-f0e4745c3e18.png)
SCREENSHOT 2: Auto hammer placed down, unpowered (no issues)

![2021-07-26_14 42 25](https://user-images.githubusercontent.com/87985958/127001048-b6bb7cda-ca69-496e-9642-c045cd904d5c.png)
SCREENSHOT 3: Auto hammer placed down, powered with solar panel/tested with other power inputs (no issue)

![2021-07-26_14 42 42](https://user-images.githubusercontent.com/87985958/127001224-4443f9a2-563d-4851-8996-68e7568374ed.png)
SCREENSHOT 4: Auto hammer provided with cobblestone, now workings, graphical errors commence: sky altered, surrounding items no longer visible (not removed, just invisible) 

![2021-07-26_14 42 52](https://user-images.githubusercontent.com/87985958/127001513-fcde5699-7a87-4149-89a1-09b62478f74c.png)
SCREENSHOT 5: Auto hammer deleted, items return to visible and sky is normal again.

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.1.63
Ex Compressum 1.16.5-4.0.4

**Additional context**
Sorry if this is unrelated to the mod, however as the issue seems to arise solely through use of the auto hammer, it felt pertinent to report here first. 
This is a new world, and the only items I've placed are vanilla fences, a chest, cyclic cables, solar flux reborn solar panels and the above auto items. I do have about 50 mods in total, as well as shaders/texture pack installed, if that is relevant.

Log report, lots of repeats of:
[14:12:45] [Render thread/WARN]: Unable to resolve texture due to reference chain texture->texture in exnihilosequentia:block/mesh_base

Gist link for log:
https://gist.github.com/xdelphii/0ce94fc653f26f1ca21afe52e92cedb7

**Comment by jinkhya** [comment] 2021-08-01 11:54
I'm also experiencing this but it's caused by shaders. Using optifine without shaders, or no optifine at all doesn't cause this. I've given up on shaders on packs that use excompressum because it gets quite messy visually :) That being said if it was fixed that'd be awesome !

**Comment by Arjuna75** [comment] 2021-08-15 10:44
I also got a problem using Auto Hammer and Auto Copressed Hammer. The problem occurs when crushing ore. All objects become translucent.
No shaders, everything is fine. But it's impossible to play with shaders :(
**Forge 36.2.2**, **ExCompressum_1.16.5-4.0.4.jar**, **OptiFine_1.16.5_HD_U_G8.jar**...
Shaders: **SEUS Renewed 1.01**, **Complementary Shaders 3.13-4.1**, **Chocapic13 V9**

![2021-08-15_13 23 37](https://user-images.githubusercontent.com/24700681/129475557-5aff1689-122d-45ef-9563-9a7f18fd6418.png)
![2021-08-15_13 23 23](https://user-images.githubusercontent.com/24700681/129475555-a070e3ae-aba7-4a53-b871-3e347379c944.png)

**Comment by djoveryde** [comment] 2021-11-02 21:34
Not sure if its the issue but perhaps have an option to disable animations on the autohammer, wondering if that is the issue with shaders.

**Comment by rVanix** [comment] 2022-01-17 07:00
Is it fixed yet? Because I really want to play this mod in my pack

**Comment by BlayTheNinth** [comment] 2022-06-27 18:29
Closing since shaders aren't supported

**Closed as not planned by BlayTheNinth** 2022-06-27 18:29 UTC
Labels: Bug, Caused by Another Mod
